# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('couleur', models.CharField(default='#4f6bed', help_text="Couleur d'affichage dans l'emploi du temps (#RRGGBB).", max_length=7)),
            ],
            options={
                'verbose_name': 'matière',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('capacite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='capacité')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. 2026-2027', max_length=20, unique=True, verbose_name='libellé')),
                ('debut', models.DateField(verbose_name='début')),
                ('fin', models.DateField()),
                ('active', models.BooleanField(default=False, help_text='Une seule année active à la fois.')),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='une_seule_annee_active')],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex. 3e A, Tle D', max_length=20)),
                ('niveau', models.CharField(blank=True, help_text='Ex. 3e, Terminale', max_length=20)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='scolarite.anneescolaire')),
                ('professeur_principal', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Coefficient de la matière pour la moyenne générale.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='scolarite.classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='enseignements', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enseignements', to='scolarite.matiere')),
            ],
            options={
                'ordering': ['classe', 'matiere'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex. 1er trimestre', max_length=30)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('debut', models.DateField(verbose_name='début')),
                ('fin', models.DateField()),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='scolarite.anneescolaire')),
            ],
            options={
                'verbose_name': 'période',
                'ordering': ['annee', 'ordre'],
            },
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('annee', 'nom'), name='classe_nom_unique'),
        ),
        migrations.AddConstraint(
            model_name='enseignement',
            constraint=models.UniqueConstraint(fields=('classe', 'matiere'), name='enseignement_unique'),
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.UniqueConstraint(fields=('annee', 'ordre'), name='periode_ordre_unique'),
        ),
    ]
