# Generated by Django 5.2.17 on 2026-10-05 09:28

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('fichier', models.FileField(storage=core.storage.StockagePrive(), upload_to=core.storage.CheminAleatoire('documents'))),
                ('publie_le', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scolarite.classe')),
            ],
            options={
                'verbose_name': "document de l'établissement",
                'verbose_name_plural': "documents de l'établissement",
                'ordering': ['-publie_le'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('REUNION', 'Réunion'), ('EXAMEN', 'Examen'), ('VACANCES', 'Vacances'), ('SORTIE', 'Sortie'), ('CULTURE', 'Culture et sport'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10)),
                ('debut', models.DateTimeField(verbose_name='début')),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('classe', models.ForeignKey(blank=True, help_text="Vide = tout l'établissement.", null=True, on_delete=django.db.models.deletion.CASCADE, to='scolarite.classe')),
            ],
            options={
                'verbose_name': 'événement',
                'ordering': ['debut'],
            },
        ),
    ]
