# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('TELECHARGEMENT', 'Téléchargement'), ('EXPORT', 'Export de données'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression / anonymisation')], max_length=15)),
                ('objet', models.CharField(help_text='Ressource concernée', max_length=200)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entrée du journal d'accès",
                'verbose_name_plural': "journal d'accès",
                'ordering': ['-date'],
            },
        ),
    ]
