# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField(max_length=5000)),
                ('pour_eleves', models.BooleanField(default=True, verbose_name='élèves')),
                ('pour_parents', models.BooleanField(default=True, verbose_name='parents')),
                ('pour_enseignants', models.BooleanField(default=True, verbose_name='enseignants')),
                ('importante', models.BooleanField(default=False, help_text='Mise en avant sur le tableau de bord.')),
                ('publiee_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(blank=True, help_text="Laisser vide pour tout l'établissement.", null=True, on_delete=django.db.models.deletion.CASCADE, to='scolarite.classe')),
            ],
            options={
                'ordering': ['-publiee_le'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=150)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('dernier_message_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dernier_message_le'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.TextField(max_length=5000)),
                ('envoye_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messagerie.conversation')),
            ],
            options={
                'ordering': ['envoye_le'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_lecture', models.DateTimeField(blank=True, null=True)),
                ('archivee', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='messagerie.conversation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='messagerie.Participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MESSAGE', 'Nouveau message'), ('ANNONCE', 'Information'), ('ABSENCE', 'Absence / retard'), ('NOTE', 'Nouvelle note'), ('EDT', 'Emploi du temps'), ('DEVOIR', 'Devoir'), ('BULLETIN', 'Bulletin')], max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('lien', models.CharField(blank=True, max_length=300)),
                ('importante', models.BooleanField(default=False)),
                ('lue', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='messagerie__destina_f93ab5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('conversation', 'utilisateur'), name='participation_unique'),
        ),
    ]
