# Generated by Django 5.2.17 on 2026-10-05 09:28

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='piece_jointe',
            field=models.FileField(blank=True, storage=core.storage.StockagePrive(), upload_to=core.storage.CheminAleatoire('messages'), validators=[core.validators.valider_justificatif]),
        ),
    ]
