# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='scolarite.classe'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'ELEVE'}, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lienparenteleve',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_parents', to='accounts.eleve'),
        ),
        migrations.AddField(
            model_name='lienparenteleve',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='liens_enfants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='enfants', through='accounts.LienParentEleve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='lienparenteleve',
            constraint=models.UniqueConstraint(fields=('parent', 'eleve'), name='lien_parent_eleve_unique'),
        ),
    ]
