# Generated by Django 5.2.17 on 2026-10-05 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences_push',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_empreinte',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name='AppareilPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.CharField(max_length=200, unique=True)),
                ('plateforme', models.CharField(blank=True, max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('vu_le', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appareil (notifications push)',
                'verbose_name_plural': 'appareils (notifications push)',
            },
        ),
    ]
