# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('bareme', models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Note maximale (ex. 20, 10, 40).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='barème')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('publiee', models.BooleanField(default=True, help_text='Décochez pour saisir les notes sans les rendre visibles tout de suite.', verbose_name='visible par les élèves et parents')),
                ('creee_le', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='scolarite.enseignement')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='scolarite.periode')),
            ],
            options={
                'verbose_name': 'évaluation',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('statut', models.CharField(choices=[('NOTEE', 'Notée'), ('ABSENT', 'Absent (non comptée)'), ('DISPENSE', 'Dispensé (non comptée)'), ('NON_RENDU', 'Non rendu (compte 0)')], default='NOTEE', max_length=10)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.evaluation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'eleve'), name='une_note_par_eleve_et_evaluation')],
            },
        ),
    ]
