# Generated by Django 5.2.17 on 2026-10-02 09:44

import core.fields
import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('type', models.CharField(choices=[('ABSENCE', 'Absence'), ('RETARD', 'Retard')], default='ABSENCE', max_length=8)),
                ('minutes_retard', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NON_JUSTIFIEE', 'Non justifiée'), ('EN_ATTENTE', 'Justificatif en attente de validation'), ('JUSTIFIEE', 'Justifiée'), ('REFUSEE', 'Justification refusée')], db_index=True, default='NON_JUSTIFIEE', max_length=14)),
                ('saisie_le', models.DateTimeField(auto_now_add=True)),
                ('motif', core.fields.EncryptedTextField(blank=True, help_text='Donnée chiffrée.')),
                ('justificatif', models.FileField(blank=True, storage=core.storage.StockagePrive(), upload_to=core.storage.CheminAleatoire('justificatifs'), validators=[core.validators.valider_justificatif])),
                ('justifiee_le', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date', 'creneau__heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fait_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
