# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absences', '0001_initial'),
        ('accounts', '0002_initial'),
        ('edt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='creneau',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour une absence à la journée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences', to='edt.creneau'),
        ),
        migrations.AddField(
            model_name='absence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='accounts.eleve'),
        ),
        migrations.AddField(
            model_name='absence',
            name='justifiee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='saisie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='traitee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appel',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='edt.creneau'),
        ),
        migrations.AddField(
            model_name='appel',
            name='fait_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(condition=models.Q(('creneau__isnull', False)), fields=('eleve', 'date', 'creneau'), name='une_absence_par_eleve_et_cours'),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(condition=models.Q(('creneau__isnull', True)), fields=('eleve', 'date'), name='une_absence_journee_par_eleve'),
        ),
        migrations.AddConstraint(
            model_name='appel',
            constraint=models.UniqueConstraint(fields=('creneau', 'date'), name='un_appel_par_cours'),
        ),
    ]
