# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(max_length=600)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='accounts.eleve')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='scolarite.enseignement')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='scolarite.periode')),
            ],
            options={
                'verbose_name': 'appréciation',
                'constraints': [models.UniqueConstraint(fields=('eleve', 'enseignement', 'periode'), name='appreciation_unique')],
            },
        ),
        migrations.CreateModel(
            name='AppreciationGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True, max_length=1000)),
                ('mention', models.CharField(blank=True, choices=[('', '—'), ('FELICITATIONS', 'Félicitations'), ('COMPLIMENTS', 'Compliments'), ('ENCOURAGEMENTS', 'Encouragements'), ('AVERT_TRAVAIL', 'Avertissement travail'), ('AVERT_CONDUITE', 'Avertissement conduite')], default='', max_length=15)),
                ('modifiee_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations_generales', to='accounts.eleve')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations_generales', to='scolarite.periode')),
            ],
            options={
                'verbose_name': 'appréciation générale',
                'verbose_name_plural': 'appréciations générales',
                'constraints': [models.UniqueConstraint(fields=('eleve', 'periode'), name='appreciation_generale_unique')],
            },
        ),
        migrations.CreateModel(
            name='PublicationBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publie_le', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='scolarite.classe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='scolarite.periode')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publication de bulletins',
                'verbose_name_plural': 'publications de bulletins',
                'constraints': [models.UniqueConstraint(fields=('classe', 'periode'), name='publication_unique')],
            },
        ),
    ]
