# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('heure_debut', models.TimeField(verbose_name='début')),
                ('heure_fin', models.TimeField(verbose_name='fin')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='scolarite.enseignement')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='scolarite.salle')),
            ],
            options={
                'verbose_name': 'créneau',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='ModificationCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('ANNULATION', 'Cours annulé'), ('SALLE', 'Changement de salle'), ('REMPLACEMENT', "Remplacement d'enseignant")], max_length=12)),
                ('motif', models.CharField(blank=True, help_text='Visible par les élèves et parents.', max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='edt.creneau')),
                ('nouvelle_salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.salle')),
                ('remplacant', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'modification de cours',
                'verbose_name_plural': 'modifications de cours',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='creneau',
            index=models.Index(fields=['jour', 'heure_debut'], name='edt_creneau_jour_5d1171_idx'),
        ),
        migrations.AddConstraint(
            model_name='modificationcours',
            constraint=models.UniqueConstraint(fields=('creneau', 'date'), name='une_modif_par_cours_et_date'),
        ),
    ]
