# Generated by Django 5.2.17 on 2026-10-05 09:28

import core.fields
import django.db.models.deletion
import finances.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_preferences_push_user_telephone_empreinte_and_more'),
        ('scolarite', '0002_documentetablissement_evenement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. 3e tranche de scolarité', max_length=120, verbose_name='libellé')),
                ('categorie', models.CharField(choices=[('SCOLARITE', 'Scolarité'), ('CANTINE', 'Cantine'), ('TRANSPORT', 'Transport'), ('AUTRE', 'Autre')], default='SCOLARITE', max_length=10)),
                ('montant', models.PositiveIntegerField(help_text='En FCFA')),
                ('echeance', models.DateField(verbose_name='échéance')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frais', to='scolarite.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='accounts.eleve')),
            ],
            options={
                'verbose_name': 'frais de scolarité',
                'verbose_name_plural': 'frais de scolarité',
                'ordering': ['echeance'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField()),
                ('moyen', models.CharField(choices=[('OM', 'Orange Money'), ('WAVE', 'Wave'), ('MTN', 'MTN MoMo'), ('MOOV', 'Moov Money'), ('CB', 'Carte bancaire'), ('ESPECES', 'Espèces (au guichet)')], max_length=8)),
                ('telephone', core.fields.EncryptedTextField(blank=True, help_text='Numéro Mobile Money (chiffré)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=10)),
                ('reference', models.CharField(default=finances.models._reference, editable=False, max_length=20, unique=True)),
                ('reference_operateur', models.CharField(blank=True, max_length=100)),
                ('numero_recu', models.CharField(blank=True, max_length=20, verbose_name='n° de reçu')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('confirme_le', models.DateTimeField(blank=True, null=True)),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='finances.fraisscolarite')),
                ('payeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
