# Generated by Django 5.2.17 on 2026-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('titre', models.CharField(max_length=150)),
                ('contenu', models.TextField(max_length=10000)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='scolarite.enseignement')),
            ],
            options={
                'verbose_name': 'contenu de séance',
                'verbose_name_plural': 'contenus de séance',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donne_le', models.DateField(verbose_name='donné le')),
                ('pour_le', models.DateField(db_index=True, verbose_name='à rendre pour le')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('duree_estimee', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='durée estimée (min)')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='scolarite.enseignement')),
            ],
            options={
                'ordering': ['pour_le', 'enseignement__matiere__nom'],
            },
        ),
        migrations.CreateModel(
            name='DevoirFait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fait_le', models.DateTimeField(auto_now_add=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cahier.devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eleve')),
            ],
        ),
        migrations.AddField(
            model_name='devoir',
            name='faits_par',
            field=models.ManyToManyField(blank=True, related_name='devoirs_faits', through='cahier.DevoirFait', to='accounts.eleve'),
        ),
        migrations.AddConstraint(
            model_name='devoirfait',
            constraint=models.UniqueConstraint(fields=('devoir', 'eleve'), name='devoir_fait_unique'),
        ),
    ]
