# Generated by Django 5.2.17 on 2026-10-05 09:28

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='piece_jointe',
            field=models.FileField(blank=True, help_text='Énoncé ou document (PDF, image).', storage=core.storage.StockagePrive(), upload_to=core.storage.CheminAleatoire('devoirs')),
        ),
        migrations.AddField(
            model_name='devoirfait',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='TERMINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='devoirfait',
            name='fait_le',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
